- id: doi:10.1073/pnas.2407990121
  type: paper
  description: We explored how a simple retrovirus, Mason-Pfizer monkey virus (M-PMV) to facilitate its replication process, utilizes DHX15, a cellular RNA helicase, typically engaged in RNA processing.
  date: 2024-09-25
  image: images/AD_pub.jpg
  buttons:
    - type: website
      link: https://pmc.ncbi.nlm.nih.gov/articles/PMC11459146/

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
